Repository ZumitoTeam/zumito-bot, pull requests merged in 2022-06, with the labels that each got.

#19 Add workflow for changelog generation on tag created
  .github/workflows/changelog.yml
Labels: development enhancement

#20 Refactor deploy workflow
  .github/workflows/deploy.yml
Labels: refactor

#30 Generate changelog after tag creation
  .github/workflows/deploy.yml
Labels: enhancement

#35 🐛 Slahscommand bug fix
  commands/info/serverinfo.js
Labels: bug

#41 Fix changelog generator
  .github/workflows/deploy.yml
Labels: bug

#40 Add guild model
  commands/admin/prefix.js
  jsconfig.json
  models/guild.js
  modules/utils/data.js
  package.json
Labels: development enhancement
